// example/solid/src/App.tsx
import { mountExampleDashboard } from "@example/shared/dashboard-client";
import { onCleanup, onMount } from "solid-js";

export default function App() {
  let root: HTMLDivElement | undefined;

  onMount(() => {
    if (!root) return;
    const cleanup = mountExampleDashboard({
      root,
      frameworkId: "solid",
    });

    onCleanup(() => {
      cleanup();
    });
  });

  return (
    <div
      ref={(el) => {
        root = el;
      }}
    />
  );
}

// example/react/src/App.tsx
import { mountExampleDashboard } from "@example/shared/dashboard-client";
import { useEffect, useRef } from "react";

export default function App() {
  const rootRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    const root = rootRef.current;
    if (!root) {
      throw new Error("Missing dashboard root");
    }

    const cleanup = mountExampleDashboard({
      root,
      frameworkId: "react",
    });
    return () => {
      cleanup();
    };
  }, []);

  return <div ref={rootRef} />;
}
