// example/nuxt/app.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue";

import { mountExampleDashboard } from "@example/shared/dashboard-client";

const root = ref<HTMLElement | null>(null);
let cleanup: (() => void) | null = null;

onMounted(() => {
  if (!root.value) {
    throw new Error("Missing dashboard root");
  }

  cleanup = mountExampleDashboard({
    root: root.value,
    frameworkId: "nuxt",
  });
});

onUnmounted(() => {
  cleanup?.();
  cleanup = null;
});
</script>

<template>
  <div ref="root" />
</template>

// example/react/src/App.tsx
import { mountExampleDashboard } from "@example/shared/dashboard-client";
import { useEffect, useRef } from "react";

export default function App() {
  const rootRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    const root = rootRef.current;
    if (!root) {
      throw new Error("Missing dashboard root");
    }

    const cleanup = mountExampleDashboard({
      root,
      frameworkId: "react",
    });
    return () => {
      cleanup();
    };
  }, []);

  return <div ref={rootRef} />;
}
