// example/solid/src/main.tsx
import "@example/shared/layout.css";
import { applyTheme, getInitialTheme } from "@example/shared/theme";
import { render } from "solid-js/web";

import App from "./App";

applyTheme(getInitialTheme());

const root = document.getElementById("root");
if (!root) {
  throw new Error("Root element #root not found");
}

render(() => <App />, root);

// example/react/src/main.tsx
import "@example/shared/layout.css";
import { applyTheme, getInitialTheme } from "@example/shared/theme";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";

import App from "./App.tsx";

applyTheme(getInitialTheme());

const rootEl = document.getElementById("root");
if (!rootEl) throw new Error("Root element #root not found");
createRoot(rootEl).render(
  <StrictMode>
    <App />
  </StrictMode>,
);
