// examples/vue/src/App.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from "vue";
import "demo/overlay";
import { Moon, Sun } from "lucide-vue-next";
import { applyTheme, getInitialTheme, toggleTheme } from "example-ui/theme";
import type { Theme } from "example-ui/theme";
import { createDemoApi } from "demo/overlay";
import type { BridgeSocketBridgeState } from "demo/overlay";
import { phaseBadgeClass, transportBadgeClass } from "example-ui/bridge";
import VueIcon from "./components/icons/Vue.vue";

const theme = ref<Theme>(getInitialTheme());
const bridge = ref<BridgeSocketBridgeState | null>(null);
const actionLoading = ref<string | null>(null);

const handleToggle = () => {
  const next = toggleTheme(theme.value);
  theme.value = next;
  applyTheme(next);
};

const api = createDemoApi();

const refresh = async () => {
  try { bridge.value = await api.getBridgeState(); } catch {}
};

const handleAction = async (action: "start" | "restart" | "stop") => {
  actionLoading.value = action;
  try {
    if (action === "start") await api.startRuntime();
    else if (action === "restart") await api.restartRuntime();
    else await api.stopRuntime();
    bridge.value = await api.getBridgeState();
  } catch {}
  actionLoading.value = null;
};


let interval: ReturnType<typeof setInterval>;

onMounted(() => {
  applyTheme(theme.value);
  refresh();
  interval = setInterval(refresh, 2000);
});

onUnmounted(() => clearInterval(interval));
</script>

<template>
  <div class="dp-page">
    <div class="dp-container">
      <header class="dp-header">
        <div class="dp-header-left">
          <h1>Demo</h1>
          <div class="dp-pill" style="background-color: #42b883">
            <VueIcon class="dp-pill-icon" style="color: white" aria-hidden="true" />
            <p style="color: white">Vue + Vite</p>
          </div>
        </div>
      </header>

      <div class="dp-card">
        <div class="dp-card-header">
          <p class="dp-card-title">Bridge</p>
        </div>
        <div class="dp-card-content">
          <div class="dp-frame">
            <div class="dp-frame-body">
              <div class="dp-status-row">
                <span class="dp-status-label">Transport</span>
                <span :class="transportBadgeClass(bridge?.transportState ?? null)">{{ bridge?.transportState ?? '—' }}</span>
              </div>
              <div class="dp-status-row">
                <span class="dp-status-label">Runtime</span>
                <span :class="phaseBadgeClass(bridge?.runtime.phase ?? null)">{{ bridge?.runtime.phase ?? '—' }}</span>
              </div>
              <div v-if="bridge?.runtime.url" class="dp-status-row">
                <span class="dp-status-label">URL</span>
                <span class="dp-status-value">{{ bridge.runtime.url }}</span>
              </div>
            </div>
            <div class="dp-frame-footer">
              <button class="dp-btn" :disabled="!!actionLoading || bridge?.runtime.phase === 'starting' || bridge?.runtime.phase === 'stopping' || bridge?.runtime.phase === 'running'" @click="handleAction('start')">
                {{ actionLoading === 'start' ? 'Starting…' : 'Start' }}
              </button>
              <button class="dp-btn" :disabled="!!actionLoading || bridge?.runtime.phase === 'starting' || bridge?.runtime.phase === 'stopping' || bridge?.runtime.phase === 'stopped' || bridge?.runtime.phase === 'error' || !bridge" @click="handleAction('restart')">
                {{ actionLoading === 'restart' ? 'Restarting…' : 'Restart' }}
              </button>
              <button class="dp-btn" :disabled="!!actionLoading || bridge?.runtime.phase === 'starting' || bridge?.runtime.phase === 'stopping' || bridge?.runtime.phase === 'stopped' || bridge?.runtime.phase === 'error' || !bridge" @click="handleAction('stop')">
                {{ actionLoading === 'stop' ? 'Stopping…' : 'Stop' }}
              </button>
            </div>
          </div>
        </div>
      </div>
      <button class="dp-icon-btn" @click="handleToggle" aria-label="Toggle theme" style="align-self: center">
        <Sun v-if="theme === 'dark'" :size="20" />
        <Moon v-else :size="20" />
      </button>
    </div>
  </div>
</template>

// examples/react/src/App.tsx
import { type BridgeSocketBridgeState, createDemoApi } from "demo/overlay";
import { phaseBadgeClass, transportBadgeClass } from "example-ui/bridge";
import {
  type Theme,
  applyTheme,
  getInitialTheme,
  toggleTheme,
} from "example-ui/theme";
import { Moon, Sun } from "lucide-react";
import { useEffect, useState } from "react";

import { React as ReactIcon } from "./components/icons/React";

export default function App() {
  const [theme, setTheme] = useState<Theme>(getInitialTheme);
  const [bridge, setBridge] = useState<BridgeSocketBridgeState | null>(null);
  const [actionLoading, setActionLoading] = useState<string | null>(null);

  useEffect(() => {
    applyTheme(getInitialTheme());
    const api = createDemoApi();
    const refresh = async () => {
      try {
        setBridge(await api.getBridgeState());
      } catch {
        /* ignore */
      }
    };
    refresh();
    const id = setInterval(refresh, 2000);
    return () => clearInterval(id);
  }, []);

  const handleAction = async (action: "start" | "restart" | "stop") => {
    const api = createDemoApi();
    setActionLoading(action);
    try {
      if (action === "start") await api.startRuntime();
      else if (action === "restart") await api.restartRuntime();
      else await api.stopRuntime();
      setBridge(await api.getBridgeState());
    } catch {
      /* ignore */
    }
    setActionLoading(null);
  };

  const phase = bridge?.runtime.phase ?? null;
  const transportState = bridge?.transportState ?? null;
  const url = bridge?.runtime.url ?? null;
  const isTransitioning =
    actionLoading !== null || phase === "starting" || phase === "stopping";

  const handleToggle = () => {
    const next = toggleTheme(theme);
    setTheme(next);
    applyTheme(next);
  };

  return (
    <div className="dp-page">
      <div className="dp-container">
        <header className="dp-header">
          <div className="dp-header-left">
            <h1>Demo</h1>
            <div className="dp-pill" style={{ backgroundColor: "#61DAFB" }}>
              <ReactIcon
                className="dp-pill-icon"
                style={{ color: "black" }}
                aria-hidden="true"
              />
              <p style={{ color: "black" }}>React + Vite</p>
            </div>
          </div>
        </header>

        <div className="dp-card">
          <div className="dp-card-header">
            <p className="dp-card-title">Bridge</p>
          </div>
          <div className="dp-card-content">
            <div className="dp-frame">
              <div className="dp-frame-body">
                <div className="dp-status-row">
                  <span className="dp-status-label">Transport</span>
                  <span className={transportBadgeClass(transportState)}>
                    {transportState ?? "—"}
                  </span>
                </div>
                <div className="dp-status-row">
                  <span className="dp-status-label">Runtime</span>
                  <span className={phaseBadgeClass(phase)}>{phase ?? "—"}</span>
                </div>
                {url && (
                  <div className="dp-status-row">
                    <span className="dp-status-label">URL</span>
                    <span className="dp-status-value">{url}</span>
                  </div>
                )}
              </div>
              <div className="dp-frame-footer">
                <button
                  className="dp-btn"
                  disabled={isTransitioning || phase === "running"}
                  onClick={() => handleAction("start")}
                >
                  {actionLoading === "start" ? "Starting…" : "Start"}
                </button>
                <button
                  className="dp-btn"
                  disabled={
                    isTransitioning ||
                    phase === "stopped" ||
                    phase === "error" ||
                    phase === null
                  }
                  onClick={() => handleAction("restart")}
                >
                  {actionLoading === "restart" ? "Restarting…" : "Restart"}
                </button>
                <button
                  className="dp-btn"
                  disabled={
                    isTransitioning ||
                    phase === "stopped" ||
                    phase === "error" ||
                    phase === null
                  }
                  onClick={() => handleAction("stop")}
                >
                  {actionLoading === "stop" ? "Stopping…" : "Stop"}
                </button>
              </div>
            </div>
          </div>
        </div>
        <button
          className="dp-icon-btn"
          onClick={handleToggle}
          aria-label="Toggle theme"
          style={{ alignSelf: "center" }}
        >
          {theme === "dark" ? <Sun size={20} /> : <Moon size={20} />}
        </button>
      </div>
    </div>
  );
}
